---
stages:
  - lint

cache:
  key: $CI_JOB_STAGE

lint:yaml:
  stage: lint
  image:
    name: alpine:3.23
    pull_policy: if-not-present
  before_script:
    - apk add --no-cache yamllint
  script: yamllint .

lint:docker-compose:
  stage: lint
  image:
    name: zavoloklom/dclint:3.1.0-alpine
    pull_policy: if-not-present
    entrypoint: ['']
  script: /bin/dclint . -c .dclint.conf.json
