---
stages:
  - lint

cache:
  key: $CI_JOB_STAGE

lint:yaml:
  stage: lint
  image: alpine:3.20
  before_script:
    - apk add --no-cache yamllint
  script: yamllint .

lint:docker-compose:
  stage: lint
  image: archlinux:latest
  before_script:
    - pacman -Syy --noconfirm docker-compose
  script: docker-compose config
