---
version: "3.3"
services:
  etherpad:
    image: k3k-etherpad:latest
    volumes:
      - type: bind
        source: ./APIKEY.txt
        target: /opt/etherpad-lite/APIKEY.txt
    environment:
      - EDIT_ONLY=true
      - ADMIN_USER=admin
      - ADMIN_PASSWORD=admin
      - SOFFICE=/usr/bin/soffice
    ports:
      - "9001:9001"
