---
version: '3.3'
services:
  etherpad:
    image: git.opentalk.dev:5050/opentalk/backend/containers/etherpad:latest
    volumes:
      - type: bind
        source: ./etherpad/APIKEY.txt
        target: /opt/etherpad-lite/APIKEY.txt
    environment:
      # Set TRUST_PROXY if the etherpad is behind a reverse proxy
      # - TRUST_PROXY=true
      - ADMIN_USER=admin
      - ADMIN_PASSWORD=admin
    ports:
      - 9001:9001
