---
version: '3.3'
networks:
    rabbitmq: null
    redis: null
    postgres: null
services:
    postgres:
        image: postgres:13-alpine
        environment:
            POSTGRES_DB: opentalk
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: password123
            POSTGRES_HOST_AUTH_METHOD: trust
        ports:
            - 5432:5432
        volumes:
            - ./pg_data:/var/lib/postgresql/data
            - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
        command:
            - postgres
            - -c
            - shared_preload_libraries=pg_stat_statements
        networks:
            - postgres
    turn:
        image: coturn/coturn:latest
        network_mode: host
        command:
            - --use-auth-secret
            - --static-auth-secret=opentalk
            - --realm=opentalk.dev
    janus:
        image: git.opentalk.dev:5050/opentalk/ot-janus-gateway:0.12.4-2
        command:
            - janus
        network_mode: host
        environment:
            - WAITTIMEOUT=30
            - RABBITMQ_HOST=localhost
            - JANUS_EXCHANGE=janus-exchange
            - JANUS_EXCHANGE_TYPE=topic
            - JANUS_QUEUE_INCOMING=to-janus
            - JANUS_ROUTING_KEY_OUTGOING=from-janus
            - JANUS_ICE_IF=ens192
            - JANUS_EVENT_LOOPS=92
            - JANUS_ICE_LITE=true
            #            - JANUS_DISABLE_WEBSOCKET=true
            - JANUS_UDP_PORT_RANGE=20000:25000
            - JANUS_IGNORE_MDS=true # remove if not wanted
            - JANUS_HTTP_ADMIN=true
        depends_on:
            - rabbitmq
    rabbitmq:
        image: rabbitmq:3-management
        environment:
            RABBITMQ_SERVER_ADITIONAL_ERL_ARGS: -rabbit log.console.level=debug
        ports:
            - 8280:15672
            - 5672:5672
        networks:
            - rabbitmq
    redis:
        image: redis:alpine
        command:
            - /usr/local/etc/redis/redis.conf
        volumes:
            - ./redis/redis.conf:/usr/local/etc/redis/redis.conf:Z
        ports:
            - 6379:6379
        networks:
            - redis
    minio:
        image: minio/minio:latest
        volumes:
            - ./minio/storage:/data
        entrypoint: ''
        command: >
            sh -c '
            mkdir -p /data/controller &&
            /usr/bin/docker-entrypoint.sh server /data --address ":9555" --console-address ":9556"
            '
        environment:
            MINIO_ROOT_USER: minioadmin
            MINIO_ROOT_PASSWORD: minioadmin
        ports:
            - 9555:9555
            - 9556:9556
