---
version: "3.3"
networks:
  postgres: null
services:
  keycloak:
    image: quay.io/keycloak/keycloak:19.0
    restart: always
    command:
      - start-dev
      - --import-realm
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres/keycloak
      KC_DB_USERNAME: postgres
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      # KC_HOSTNAME: keycloak
      KC_HTTP_RELATIVE_PATH: /auth
    volumes:
      - ./keycloak:/opt/keycloak/data/import:Z
    ports:
      - "8080:8080"
    networks:
      - postgres
    depends_on:
      - postgres
