---
version: "3.9"
networks:
    prometheus: null
volumes:
    rabbitmq-prometheus_prometheus: null
    rabbitmq-prometheus_grafana: null
services:
    prometheus:
        # https://hub.docker.com/r/prom/prometheus/tags
        image: quay.io/prometheus/prometheus:latest
        networks:
            - "prometheus"
        ports:
            - "9090:9090"
        volumes:
            - rabbitmq-prometheus_prometheus:/prometheus
            - ./prometheus.yml:/etc/prometheus/prometheus.yml
    node-exporter:
        command:
            - '--path.procfs=/host/proc'
            - '--path.rootfs=/rootfs'
            - '--path.sysfs=/host/sys'
            - '--collector.filesystem.ignored-mount-points=^/(sys|proc|dev|host|etc)($$|/)'
        expose:
            - 9100
            # https://hub.docker.com/r/prom/node-exporter/tags
        image: quay.io/prometheus/node-exporter:latest
        networks:
            - "prometheus"
        volumes:
            - /proc:/host/proc:ro
            - /sys:/host/sys:ro
            - /:/rootfs:ro
    redis-exporter:
        image: quay.io/oliver006/redis_exporter
        environment:
            - REDIS_EXPORTER_COUNT_KEYS=k3k-signaling:runner:*,k3k-signaling:room=*:participant=*:namespace=media:state
        networks:
            - "prometheus"

    grafana:
        # https://hub.docker.com/r/grafana/grafana/tags
        image: grafana/grafana:8.2.3
        ports:
            - "9000:3000"
        networks:
            - "prometheus"
        volumes:
            - rabbitmq-prometheus_grafana:/var/lib/grafana
            - ./grafana/dashboards.yml:/etc/grafana/provisioning/dashboards/rabbitmq.yaml
            - ./grafana/datasources.yml:/etc/grafana/provisioning/datasources/prometheus.yaml
            - ./grafana/dashboards:/dashboards
        environment:
            # https://grafana.com/plugins/flant-statusmap-panel
            # https://grafana.com/plugins/grafana-piechart-panel
            # https://grafana.com/plugins/grafana-polystat-panel
            # https://grafana.com/plugins/jdbranham-diagram-panel
            # https://grafana.com/plugins/michaeldmoore-multistat-panel
            # https://grafana.com/plugins/vonage-status-panel
            # https://grafana.com/plugins/yesoreyeram-boomtable-panel
            GF_INSTALL_PLUGINS: "flant-statusmap-panel,grafana-piechart-panel"
