---
volumes:
  rabbitmq-prometheus_prometheus: null
  rabbitmq-prometheus_grafana: null

services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: opentalk
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password123
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - 127.0.0.1:5432:5432
    volumes:
      - ./pg_data${COMPOSE_PROJECT_NAME:+_$COMPOSE_PROJECT_NAME}:/var/lib/postgresql/data
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    command:
      - postgres
      - -c
      - shared_preload_libraries=pg_stat_statements
    healthcheck:
      test:
        - CMD-SHELL
        - pg_isready -U postgres -d opentalk
      interval: 10s
      timeout: 5s
      retries: 3

  livekit:
    image: livekit/livekit-server:v1.8
    network_mode: host
    restart: always
    command: --config /livekit.yaml --dev --node-ip 127.0.0.1
    volumes:
      - ./livekit.yaml:/livekit.yaml

  rabbitmq:
    image: rabbitmq:4-management
    environment:
      RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS: -rabbit log.console.level=debug
    ports:
      - 127.0.0.1:8280:15672
      - 127.0.0.1:5672:5672
    healthcheck:
      test: [CMD, rabbitmq-diagnostics, check_port_connectivity]
      start_period: 120s
      start_interval: 10s
      interval: 180s
      timeout: 20s
      retries: 3

  redis:
    profiles:
      - extras
    image: redis:alpine
    command:
      - /usr/local/etc/redis/redis.conf
    volumes:
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf:Z
    ports:
      - 127.0.0.1:6379:6379

  minio:
    image: minio/minio:latest
    volumes:
      - ./minio${COMPOSE_PROJECT_NAME:+_$COMPOSE_PROJECT_NAME}/storage:/data
    entrypoint: ''
    command: >
      sh -c '
      mkdir -p /data/controller &&
      /usr/bin/docker-entrypoint.sh server /data --address ":9555" --console-address ":9556"
      '
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - 127.0.0.1:9555:9555
      - 127.0.0.1:9556:9556

  controller:
    image: git.opentalk.dev:5050/opentalk/backend/services/controller:dev
    profiles:
      - backend
    volumes:
      - ./controller/config.toml:/controller/config.toml
    environment:
      - RUST_LOG=debug,rusttls=info,tokio_tungstenite=info,tungstenite=info
      # - OPENTALK_CTRL__LOGGING__OTLP_TRACING_ENDPOINT="http://localhost:4317" # enables tracing (see jaeger)
      # - OPENTALK_CTRL__KEYCLOAK__BASE_URL=http://central-testing-keycloak:8080/auth
      # - OPENTALK_CTRL__KEYCLOAK__REALM=opentalk
      # - OPENTALK_CTRL__ETHERPAD__URL=http://etherpad/
      # - OPENTALK_CTRL__ETHERPAD__API_KEY=secret
    network_mode: host
    depends_on:
      postgres:
        condition: service_healthy
        restart: true
      livekit:
        condition: service_started
        restart: true
      keycloak:
        condition: service_healthy
        restart: true

  etherpad:
    image: git.opentalk.dev:5050/opentalk/backend/containers/etherpad:latest
    profiles:
      - etherpad
    volumes:
      - type: bind
        source: ./etherpad/APIKEY.txt
        target: /opt/etherpad-lite/APIKEY.txt
    environment:
      # Set TRUST_PROXY if the etherpad is behind a reverse proxy
      # - TRUST_PROXY=true
      - ADMIN_USER=admin
      - ADMIN_PASSWORD=admin
    ports:
      - 127.0.0.1:9001:9001

  ndt:
    image: measurementlab/ndt-server:latest
    profiles:
      - extras
    volumes:
      # - ./ndt/certs:/certs
      # - ./ndt/html:/html
      - ./ndt/datadir:/datadir
    cap_drop:
      - ALL
    ports:
      # - 127.0.0.1:10443:4443
      - 127.0.0.1:10081:8080
    command:
      # - -cert
      # - /certs/cert.pem
      # - -key
      # - /certs/key.pem
      - -datadir
      - /datadir
      # - -ndt7_addr
      # - :4443
      - -ndt7_addr_cleartext
      - :8080

  frontend:
    image: git.opentalk.dev:5050/opentalk/frontend/web/web-app:profiling
    profiles:
      - frontend
    ports:
      - 127.0.0.1:3000:80
    environment:
      - LIVEKIT_SERVER_URL=http://localhost:7880
      - CONTROLLER_HOST=localhost:8000
      - BASE_URL=http://localhost:3000
      - OIDC_ISSUER=http://localhost:8080/auth/realms/OPENTALK
      - INSECURE=true

  prometheus:
    # https://hub.docker.com/r/prom/prometheus/tags
    image: quay.io/prometheus/prometheus:latest
    profiles:
      - metrics
    ports:
      - 127.0.0.1:9090:9090
    volumes:
      - rabbitmq-prometheus_prometheus:/prometheus
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

  node-exporter:
    image: quay.io/prometheus/node-exporter:latest
    profiles:
      - metrics
    command:
      - --path.procfs=/host/proc
      - --path.rootfs=/rootfs
      - --path.sysfs=/host/sys
      - --collector.filesystem.ignored-mount-points=^/(sys|proc|dev|host|etc)($$|/)
    expose:
      - 127.0.0.1:9100
      # https://hub.docker.com/r/prom/node-exporter/tags
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro

  redis-exporter:
    image: quay.io/oliver006/redis_exporter
    profiles:
      - metrics
    environment:
      - REDIS_EXPORTER_COUNT_KEYS=opentalk-signaling:runner:*,opentalk-signaling:room=*:participant=*:namespace=media:state

  grafana:
    # https://hub.docker.com/r/grafana/grafana/tags
    image: grafana/grafana:12.0.2
    profiles:
      - metrics
    ports:
      - 127.0.0.1:9000:3000
    volumes:
      - rabbitmq-prometheus_grafana:/var/lib/grafana
      - ./grafana/dashboards.yml:/etc/grafana/provisioning/dashboards/rabbitmq.yaml
      - ./grafana/datasources.yml:/etc/grafana/provisioning/datasources/prometheus.yaml
      - ./grafana/dashboards:/dashboards
    environment:
      # https://grafana.com/plugins/flant-statusmap-panel
      # https://grafana.com/plugins/grafana-piechart-panel
      # https://grafana.com/plugins/grafana-polystat-panel
      # https://grafana.com/plugins/jdbranham-diagram-panel
      # https://grafana.com/plugins/michaeldmoore-multistat-panel
      # https://grafana.com/plugins/vonage-status-panel
      # https://grafana.com/plugins/yesoreyeram-boomtable-panel
      GF_INSTALL_PLUGINS: flant-statusmap-panel,grafana-piechart-panel

  nextcloud:
    image: docker.io/library/nextcloud:apache
    profiles:
      - sharedfolder
    volumes:
      - ./nextcloud${COMPOSE_PROJECT_NAME:+_$COMPOSE_PROJECT_NAME}:/var/www/html
    environment:
      - SQLITE_DATABASE=nextcloud
      - NEXTCLOUD_ADMIN_USER=exampleuser
      - NEXTCLOUD_ADMIN_PASSWORD=v3rys3cr3t
    ports:
      - 127.0.0.1:9002:80

  keycloak:
    image: quay.io/keycloak/keycloak:26.1
    restart: always
    command:
      - start-dev
      - --import-realm
      - --health-enabled=true
      - --tracing-enabled=true
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres/keycloak
      KC_DB_USERNAME: postgres
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
      # KC_HOSTNAME: keycloak
      KC_HTTP_RELATIVE_PATH: /auth
      KC_TRACING_ENDPOINT: http://jaeger:4317
    volumes:
      - ./keycloak:/opt/keycloak/data/import:Z
    ports:
      - 127.0.0.1:8080:8080
    healthcheck:
      test:
        - CMD-SHELL
        - |
          exec 3<>/dev/tcp/127.0.0.1/9000 && echo "GET /auth/health/ready HTTP/1.1
          Host: localhost:9000
          User-Agent: curl/8.8.0
          Accept: */*
          " >&3 && head -7 <&3 | grep 'UP'
      start_period: 180s
      start_interval: 5s
      interval: 10s
      timeout: 5s
      retries: 3
    depends_on:
      postgres:
        condition: service_healthy
        restart: true

  recorder:
    image: git.opentalk.dev:5050/opentalk/backend/services/recorder:dev
    restart: always
    profiles:
      - recorder
    volumes:
      - ./recorder/config.toml:/recorder/config.toml
    environment:
      RUST_LOG: debug,k3k=debug,ezk=debug
      RUST_BACKTRACE: full
      GST_DEBUG: 3
    network_mode: host
    depends_on:
      rabbitmq:
        condition: service_healthy

  jaeger:
    image: quay.io/jaegertracing/jaeger:2.8.0
    profiles:
      - metrics
    ports:
      - 127.0.0.1:16686:16686
      - 127.0.0.1:4317:4317
      - 127.0.0.1:4318:4318

  smtp-mailer:
    image: git.opentalk.dev:5050/opentalk/backend/services/smtp-mailer:dev
    profiles:
      - mailer
    volumes:
      - ./smtp-mailer/config.toml:/opt/smtp-mailer/config.toml
    depends_on:
      rabbitmq:
        condition: service_healthy

  mailcrab:
    image: marlonb/mailcrab:latest
    profiles:
      - mailer
    ports:
      - 127.0.0.1:1080:1080
      - 127.0.0.1:1025:1025
