---
version: '3.9'
services:
    keycloak:
        image: quay.io/keycloak/keycloak:13.0.1
        environment:
            DB_VENDOR: h2
            KEYCLOAK_USER: admin
            KEYCLOAK_PASSWORD: admin
            KEYCLOAK_IMPORT: /tmp/keycloak/keycloak_realm_export.json
        volumes:
            - ./keycloak:/tmp/keycloak:Z
        ports:
            - 8080:8080
            - 8443:8443
    postgres:
        image: postgres:13-alpine
        environment:
            POSTGRES_DB: k3k
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: password123
            POSTGRES_HOST_AUTH_METHOD: trust
        ports:
            - 5432:5432
    turn:
        image: coturn/coturn:alpine
        command:
            - --use-auth-secret
            - --static-auth-secret=k3k
            - --realm=heinlein-video.de
        network_mode: host
    janus-1:
        image: quay.io/freswa/janus-gateway:0.11.1
        command:
            - janus
            - -d 5
        depends_on:
            - rabbit
        volumes:
            - ./janus/janus-1.transport.rabbitmq.jcfg:/etc/janus/janus.transport.rabbitmq.jcfg:Z
            - ./janus/janus.transport.http.jcfg:/etc/janus/janus.transport.http.jcfg:Z
            - ./janus/janus.transport.websockets.jcfg:/etc/janus/janus.transport.websockets.jcfg:Z
        network_mode: host
    janus-2:
        image: quay.io/freswa/janus-gateway:0.11.1
        command:
            - janus
            - -d 5
        depends_on:
            - rabbit
        volumes:
            - ./janus/janus-2.transport.rabbitmq.jcfg:/etc/janus/janus.transport.rabbitmq.jcfg:Z
            - ./janus/janus.transport.http.jcfg:/etc/janus/janus.transport.http.jcfg:Z
            - ./janus/janus.transport.websockets.jcfg:/etc/janus/janus.transport.websockets.jcfg:Z
        network_mode: host
    rabbit:
        image: rabbitmq:3.8-management-alpine
        environment:
            RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS: -rabbit consumer_timeout 1000
        ports:
            - 8280:15672
            - 5672:5672
        healthcheck:
            test: [CMD, curl, -f, http://localhost:8280]
            interval: 30s
            timeout: 10s
            retries: 5
    redis:
        image: redis:alpine
        command:
            - /usr/local/etc/redis/redis.conf
        volumes:
            - ./redis/redis.conf:/usr/local/etc/redis/redis.conf:Z
        ports:
            - 6379:6379

#  echo "nameserver 192.168.100.1" >> /etc/resolv.conf
#  pacman -S net-tools
#  netstat -ntlpu
