---
version: '3.3'

services:
  controller:
    image: git.opentalk.dev:5050/opentalk/backend/services/recorder:dev
    volumes:
      - ./recorder/config.toml:/recorder/config.toml
    environment:
      - RUST_LOG=info

    network_mode: host
