[controller]
url = "http://localhost:8000/"
api_key = { "id" = "controller", "secret" = "secret" }

[http]
api_keys = [{ "id" = "recorder", "secret" = "secret" }]

[recorder]
clock_format = "%d.%m.%y %X %Z"
